removed any plugin build added RC build in hooks and latest tagging

diff --git a/hooks/test b/hooks/test
--- a/hooks/test
+++ b/hooks/test
@@ -9,3 +9,7 @@ for VERSION in $STABLE_VERSION $MAINT_VERSION; do
   #export VERSION=$VERSION
   timeout 10m docker-compose -f docker-compose.test.yml run --rm sut || ( echo "test for docker image geoserver:$VERSION failed" && echo $VERSION >> /tmp/failed_versions )
 done
+
+for VERSION in $RC_VERSION; do
+  timeout 10m docker-compose -f docker-compose.test.yml run --rm sut || ( echo "test for docker image geoserver:$VERSION failed" && echo $VERSION >> /tmp/failed_versions )
+done
